### PR TITLE
changes for 64 bit and other fixes

### PR DESCRIPTION
**Pull request by sagarkchitnis**
Changes for the 64 bit build. Also contains other previous(not 64 bit related) changes. Please note this is a breaking change.  Will require changes from other repos as well as new third party components.

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by jablonskim** [comment]
Retest this please

**Comment by sagarkchitnis** [comment]
I am unable to see the build logs.

**Comment by sagarkchitnis** [comment]
Retest this please

**Comment by sagarkchitnis** [comment]
Retest this please

**Pull request merged**
